export { default as ServerSetting} from './System/ServerSetting.vue'
export { default as MCallSetting } from './System/MCallSetting.vue'
export { default as ResultSetting } from './System/ResultSetting.vue'
export { default as Logout } from './System/Logout.vue'

export { default as OddsSetting } from './Business/OddsSetting.vue'
export { default as BillSetting } from './Business/BillSetting.vue'
export { default as ZeroPlayer } from './Business/ZeroPlayer.vue'
export { default as AllPlayer } from './Business/AllPlayer.vue'
export { default as TableSetting} from './Business/TableSetting.vue'
export { default as ChipsBox } from './Business/ChipsBox.vue'
export { default as RemainPoint } from './Business/RemainPoint.vue'
export { default as FontReport } from './Business/FontReport.vue'
export { default as WayBillSetting } from './Business/WayBillSetting.vue'
export { default as ModifyStation } from './Business/ModifyStationNo.vue'
export { default as CopySetting } from './Business/CopySetting.vue'

export { default as SummaryFinance } from './Details/SummaryFinance.vue'
export { default as DetailFinance } from './Details/DetailFinance.vue'
export { default as BetDetail } from './Details/BetDetail.vue'
export { default as CoinDetail } from './Details/CoinDetail.vue'

export { default as Statistics} from './Others/Statistics.vue'
export { default as ClearBetSheet } from './Others/ClearBetSheet.vue'

export { default as CreatePlayerDialog } from './Players/CreatePlayer.vue'
export { default as UpdatePlayerDialog } from './Players/UpdatePlayer.vue'
export { default as DeletePlayerDialog } from './Players/DeletePlayer.vue'
export { default as TopPlayerDialog } from './Players/TopPlayer.vue'
export { default as HidePlayerDialog } from './Players/HidePlayer.vue'

export { default as NextRound } from './Results/NextRoundDialog.vue'
export { default as NextShoe } from './Results/NextShoeDialog.vue'
export { default as EditShoe } from './Results/EditShoeDialog.vue'
export { default as LockBootRound } from './Results/LockBootRound.vue'
export { default as LastRound } from './Results/LastRound.vue'

export { default as ImportTable} from './Table/ImportTable.vue'
export { default as LotteryCalculate} from './Table/LotteryCalculate.vue'
export { default as BetTableScreenshot} from './Table/BetTableScreenshot.vue'
export { default as ScoreTableScreenshot} from './Table/ScoreTableScreenshot.vue'
export { default as NextRounds} from './Table/NextRound.vue'
